// linear icon name to nerdfont icon
pub fn ico_to_nf(name: &str) -> String {
    let nf = match name {
        "Umbrella" => "  ",
        "FaceStarEyes" => "  ",
        "Radar" => "󰐷 ",
        "Chip" => " ",
        "Joystick" => "󰮂 ",
        "Battery" => " ",
        "Sound" => " ",
        "Cone" => "󱍼 ",
        "Database" => " ",
        "Terminal" => " ",
        "Watch" => "󰢗 ",
        "Clock" => "󰥔 ",
        "Lock" => "󰌾 ",
        "Compass" => "󰆋 ",
        "Server" => "󰒋 ",
        "Calendar" => " ",
        "Apple" => " ",
        "Android" => " ",
        "Page" => "󰈙 ",
        "Robot" => " ",
        "Magnify" => " ",
        "Chat" => "󰭹 ",
        "LightBulb" => "󰌵 ",
        "Alert" => "󰀨 ",
        "Mac" => " ",
        "MobilePhone" => " ",
        "Computer" => "󰍹 ",
        "Tablet" => "󰓷 ",
        "Cube" => " ",
        "Bookmark" => " ",
        "Video" => " ",
        "Sign" => " ",
        "Inbox" => " ",
        "Subscribe" => "󰂚 ",
        "Email" => " ",
        "Bucket" => "󱐕 ",
        "Label" => "󰌕 ",
        "Brush" => " ",
        "Home" => " ",
        "Camera" => "󰄀 ",
        "CameraAi" => "󰻛 ",
        "Trash" => " ",
        "GitHub" => " ",
        "GitLab" => " ",
        "Book" => " ",
        "Megaphone" => " ",
        "Checklist" => " ",
        "Education" => " ",
        "Present" => " ",
        "Feather" => " ",
        "Cross" => " ",
        "Gears" => " ",
        "Phone" => " ",
        "Image" => " ",
        "Basket" => "󰁶 ",
        "DesignTools" => " ",
        "TeeShirt" => " ",
        "Link" => " ",
        "Dashboard" => "󰨇 ",
        "CreditCard" => " ",
        "Briefcase" => " ",
        "Bank" => " ",
        "Dollar" => " ",
        "Euro" => " ",
        "Bitcoin" => " ",
        "Etherum" => "󰡪 ",
        "Solana" => "󰬚 ",
        "Cart" => "󰄐 ",
        "Shop" => " ",
        "Shield" => "󱄻 ",
        "PieChart" => " ",
        "BarChart" => "󰄨 ",
        "Chart" => " ",
        "Crown" => " ",
        "Airplane" => "󰀝 ",
        "Bike" => "󰂣 ",
        "Car" => "󰄋 ",
        "Ship" => "󰻈 ",
        "Rocket" => "󱓞 ",
        "Anchor" => " ",
        "World" => " ",
        "Asia" => " ",
        "Australia" => "󱜿 ",
        "Europe" => " ",
        "Africa" => " ",
        "SouthAmerica" => " ",
        "NorthAmerica" => " ",
        "Pin" => " ",
        "Face" => " ",
        "UnhappyFace" => " ",
        "ThumbsUp" => " ",
        "ThumbsDown" => " ",
        "Skull" => " ",
        "FaceHeartEyes" => " ",
        "FaceFlatSmile" => " ",
        "FaceMask" => "󱖆 ",
        "FaceSurprise" => " ",
        "FaceMonocle" => " ",
        "FaceSunglasses" => "󰓠 ",
        "Dna" => " ",
        "Brain" => "󰧑 ",
        "Bolt" => " ",
        "Favorite" => " ",
        "Coffee" => "󰅶 ",
        "Accessibility" => " ",
        "Burger" => " ",
        "FaceId" => "󰗆 ",
        "FootPrint" => " ",
        "Mic" => " ",
        "MusicKey" => " ",
        "Paint" => " ",
        "Pizza" => " ",
        "Ramen" => " ",
        "WindTurbine" => "󰶥 ",
        "Modem" => " ",
        "Jersey" => " ",
        "Moon" => " ",
        "Scissors" => " ",
        "Ai" => " ",
        "AiApp" => "󰩳 ",
        "AiDocument" => "󱪙 ",
        "Binocular" => " ",
        "Bluetooth" => " ",
        "Direction" => "󰇐 ",
        "Network" => "󰀂 ",
        "Policy" => "󰐂 ",
        "Routing" => " ",
        "AirTag" => " ",
        "AlarmClock" => "󰀠 ",
        "AmericanFootBall" => " ",
        "Asterisk" => " ",
        "Bandage" => " ",
        "Basketball" => "󰠆 ",
        "Bed" => " ",
        "Boombox" => "󰗜 ",
        "Bones" => " ",
        "BookOpen" => " ",
        "BowlingBall" => "󰃓 ",
        "Box" => " ",
        "BoxOpen" => " ",
        "Bus" => "󰃧 ",
        "Calculator" => " ",
        "CarPool" => "󱀕 ",
        "Chemist" => " ",
        "ClickButton" => "󰳽 ",
        "ClothHanger" => "󰋈 ",
        "Comodore" => " ",
        "Connected" => " ",
        "ConstructionBarrier" => "",
        "Conversation" => "󱐏 ",
        "Cookie" => "󰆘 ",
        "Crane" => "󰡢 ",
        "CrystalBall" => "󰬯 ",
        "DesktopWindow" => " ",
        "Dice" => " ",
        "Dino" => "",
        "DollarBill" => " ",
        "Dumbbell" => " ",
        "ElectricPlug" => " ",
        "Eraser" => " ",
        "Extinguisher" => " ",
        "Factory" => "󰈏 ",
        "Flashlight" => "󰉄 ",
        "FloppyDisk" => "󰉉 ",
        "Garage" => "󰛙 ",
        "Golf" => "󰠣 ",
        "Hack" => "󱚞 ",
        "Health" => " ",
        "Hear" => "󰟅 ",
        "Hourglass" => " ",
        "Judge" => "󰊛 ",
        "Ladder" => "󱖢 ",
        "LockerRoom" => "󰟘 ",
        "MacOS" => "󰀶 ",
        "MagicWand" => " ",
        "Magnet" => "󰍈 ",
        "Mask" => " ",
        "MilitaryTruck" => "󰔽 ",
        "MoneyStack" => " ",
        "MovingStaircase" => "󰇿 ",
        "MusicTape" => "󰧔 ",
        "NotePad" => "󱞁 ",
        "Notified" => "󱅫 ",
        "PalmTree" => "󱁕 ",
        "Pills" => "󰐂 ",
        "PingPong" => " ",
        "Pointer" => " ",
        "PokerCard" => "󰘸 ",
        "Process" => " ",
        "Rank" => "󰶼 ",
        "Runner" => " ",
        "SafetyKit" => " ",
        "Shrug" => " ",
        "Signature" => " ",
        "SoccerBall" => "󰒸 ",
        "Spaces" => "󰹑 ",
        "Speaker" => "󰓃 ",
        "Spreadsheet" => "󰧷 ",
        "Stadium" => "󰜠 ",
        "Storm" => " ",
        "Subgroup" => " ",
        "Surfer" => "󱝆 ",
        "Taxi" => " ",
        "TennisBall" => "󰔇 ",
        "TextBlock" => " ",
        "TextParagraph" => " ",
        "Tower" => " ",
        "TrafficLight" => "󰔫 ",
        "Train" => " ",
        "Tram" => "󰔬 ",
        "Union" => "󰡷 ",
        "ViewFinder" => "󰓾 ",
        "VisionPro" => "󰴰 ",
        "Wall" => "󰟾 ",
        "Wrench" => " ",
        "Write" => "󰏫 ",
        "WritingAI" => "󰷫 ",
        "Refresh" => " ",
        "Comment" => " ",
        "Attachment" => "󰁦 ",
        "Blockquote" => " ",
        "CodeBlock" => " ",
        "Brick" => "󱊍 ",
        "Meta" => " ",
        "OpenAI" => "󰴈 ",
        "Linear" => "󰰍 ",
        "Auth0" => "󱄻 ",
        "Chrome" => " ",
        "Discord" => " ",
        "Edge" => "󰇩 ",
        "Figma" => " ",
        "Firefox" => " ",
        "Intercom" => " ",
        "Notion" => " ",
        "OnePassword" => "󰢁 ",
        "Sentry" => " ",
        "Slack" => " ",
        "Zapier" => " ",
        "Zendesk" => "󰬡 ",
        _ => "",
    };
    nf.to_string()
}

pub fn p_to_nf(priority: f64) -> String {
    let nf = match priority {
        1.0 => "󰀧  ",
        2.0 => "  ",
        3.0 => "  ",
        4.0 => "  ",
        _ => "  ",
    };
    nf.to_string()
}

pub fn state_to_nf(state: &str) -> String {
    let nf = match state {
        "triage" => "󰿡 ",
        "backlog" => "󱥸 ",
        "unstarted" => " ",
        "started" => " ",
        "completed" => " ",
        "cancelled" => " ",
        _ => "",
    };
    nf.to_string()
}

#[cfg(test)]
mod tests {
    use crate::iconmap::{ico_to_nf, p_to_nf, state_to_nf};

    #[test]
    fn test_transitions() {
        assert_eq!( ico_to_nf("Umbrella"), "  ".to_string());
        assert_eq!( state_to_nf("triage"), "󰿡 ".to_string());
        assert_eq!( p_to_nf(3.0), "  ".to_string());

        assert_eq!( ico_to_nf("asdfa"), "");
        assert_eq!( p_to_nf(202.0), "  ");
        assert_eq!( state_to_nf("unknown"), "");
    }

}
